library(shiny)
library(readr)
library(dplyr)
library(factoextra)
library(readxl)
library(dplyr)
library(caTools)
library(plotrix)
library(corrplot)
library(shinythemes)
library(plotly)
library(MLmetrics)
library(DT)
library(FactoMineR)
library(ggplot2)
library(grid)
library(doBy)
library(shinyWidgets)
library(gridExtra)
library(plyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(agricolae)
library(MASS)
library(googleVis)
shinyUI(
  
  fluidPage(theme=shinytheme("flatly"),
            setBackgroundImage(src = "hh.gif"),
            
            navbarPage(
              "Analyse Senso",
              tabPanel("intoduction","                                      ",img(heigth = 900, width = 900, src = "hedhy.gif")),
              tabPanel("DATA", tabsetPanel(tabPanel("sensorial data", sidebarLayout(
                sidebarPanel(
                  fileInput("file","Upload the file", multiple = TRUE,width = '1000000000000px'), # fileinput() function is used to get the file upload contorl option
                  helpText("Please enter your data"),
                  helpText("Select the parameters below"),
                  checkboxInput(inputId = 'header', label = 'Header', value = TRUE),
                  checkboxInput(inputId = "stringAsFactors", "stringAsFactors", FALSE),
                  radioButtons(inputId = 'sep', label = 'Separator', choices = c(Comma=',',Semicolon=';',Tab='\t', Space=''), selected = ','),
                  uiOutput("selectfile")
                ),
                mainPanel(
                  uiOutput("tb")
                  
                )
                
              )),tabPanel("consumer data",sidebarLayout(
                sidebarPanel(
                  fileInput("files","Upload the file", multiple = TRUE,width = '1000000000000px'), # fileinput() function is used to get the file upload contorl option
                  helpText("Please enter your hedo data"),
                  helpText("Select the  parameters below"),
                  checkboxInput(inputId = 'header2', label = 'Header', value = TRUE),
                  checkboxInput(inputId = "stringAsFactors2", "stringAsFactors", FALSE),
                  radioButtons(inputId = 'sep2', label = 'Separator', choices = c(Comma=',',Semicolon=';',Tab='\t', Space=''), selected = ','),
                  uiOutput("seelect")
                  
                ),
                mainPanel(
                  uiOutput("affiche")
                  
                )
                
              )
              ))
              
              )     ,tabPanel("descriptive Analysis", tabsetPanel(tabPanel("data processing",tabsetPanel(tabPanel("statistical table of qualitative variables",sidebarLayout(sidebarPanel(selectInput("factee", "Type:",c("mean"="mean","sd"="sd")),
                                                                                                                                                                                     selectInput("v", "Type:", 
                                                                                                                                                                                                 c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                                     
                                                                                                                                                                                     hr(),
                                                                                                                                                                                     helpText("choisir les variable")),mainPanel( DT::dataTableOutput("thenya")))),tabPanel("statistical table of quantitative variables",DT::dataTableOutput("stable")))),tabPanel("PLOTS",
                                                                           tabsetPanel(tabPanel("Static Plots", tabsetPanel(tabPanel("variables effects",sidebarLayout(sidebarPanel(selectInput("type", "Type:",c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                        radioButtons(inputId="va",label = "select the file type",choices = list("png","pdf")),
                                                                                                                                                                        hr(),
                                                                                                                                                                        helpText("choisir les variable")),mainPanel(plotOutput("graph"),downloadButton(outputId="var4",label="Download the plot")))),tabPanel("factor effects",sidebarLayout(sidebarPanel(selectInput("js", "Type:", 
                                                                                                                                                                                                                                                                                                                                                                  c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                                                                                                                                                                                                      radioButtons(inputId="var3",label = "select the file type",choices = list("png","pdf")),
                                                                                                                                                                                                                                                                                                                                                      hr(),
                                                                                                                                                                                                                                                                                                                                                      helpText("choisir les variable")),mainPanel(plotOutput("graphe"),downloadButton(outputId="down",label="Download the plot")))),tabPanel("Stacked histogram",sidebarLayout(sidebarPanel(selectInput("varr", "Type:",c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     selectInput("varr2", "Type:", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     radioButtons(inputId="var10",label = "select the file type",choices = list("png","pdf")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     hr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     helpText("choisir les variable")),mainPanel(plotOutput("stacked"),downloadButton(outputId="var5",label="Download the plot")))),tabPanel("pies",sidebarLayout(sidebarPanel(selectInput("w", "Type:",c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     radioButtons(inputId="var6",label = "select the file type",choices = list("png","pdf")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     hr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     helpText("choisir les variable")),mainPanel(plotOutput("pieee"),downloadButton(outputId="var60",label="Download the plot")))),tabPanel("effet variable/factor",sidebarLayout(sidebarPanel(selectInput("variablee", "Type:",c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   selectInput("produit", "Type:", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   radioButtons(inputId="var8",label = "select the file type",choices = list("png","pdf")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   hr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   helpText("choisir les variable")),mainPanel(plotOutput("quatrep"),downloadButton(outputId="var88",label="Download the plot")))))),
                                                                                       # tabsetPanel(tabPanel("plot1"),tabPanel("plot2"),tabPanel("plot3"),tabPanel("plot4"),tabPanel("Plot5")),
                                                                                       tabPanel("Interactive Plots", tabsetPanel(tabPanel("plot1",sidebarLayout(sidebarPanel(selectInput("fa", "Type:", 
                                                                                                                                                                                         c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                             
                                                                                                                                                                             hr(),
                                                                                                                                                                             helpText("chose your variable")),mainPanel(plotlyOutput("esmha")))),tabPanel("plot2",plotlyOutput("tokhrej")),tabPanel("plot3",sidebarLayout(sidebarPanel(selectInput("var1", "Type:",c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                                                                                                                                                                                       selectInput("var2", "Type:", 
                                                                                                                                                                                                                                                                                                                                                   c(" "=" ","seance"="seance","juge"="juge","produit"="produit")),
                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                       hr(),
                                                                                                                                                                                                                                                                                                                                       helpText("Choisir la variable ")),mainPanel( plotlyOutput("courbee")))),tabPanel("Plot4",plotlyOutput("piess")))))))),
              tabPanel("univariate analysis",tabsetPanel(tabPanel("anova",sidebarLayout(sidebarPanel(selectInput("troiss11", "Type:", 
                                                                                                                               c(" "=" ","seance"="seance")),
                                                                                                                   selectInput("troiss22", "Type:", 
                                                                                                                               c(" "=" ","juge"="juge")),
                                                                                                                   selectInput("troiss33", "Type:", 
                                                                                                                               c(" "=" ","produit"="produit")),
                                                                                                                   selectInput("quatree11", "Type:", 
                                                                                                                               c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                   hr(),
                                                                                                                   helpText("choisir les variable")),mainPanel (verbatimTextOutput("cinq22") ))),tabPanel("TUCKY",sidebarLayout(sidebarPanel(selectInput("troiss1", "Type:", 
                                                                                                                                                                                                                                                                     c(" "=" ","seance"="seance")),
                                                                                                                                                                                                                                                         selectInput("troiss2", "Type:", 
                                                                                                                                                                                                                                                                     c(" "=" ","juge"="juge")),
                                                                                                                                                                                                                                                         selectInput("troiss3", "Type:", 
                                                                                                                                                                                                                                                                     c(" "=" ","produit"="produit")),
                                                                                                                                                                                                                                                         selectInput("quatree1", "Type:", 
                                                                                                                                                                                                                                                                     c(" "=" ","Vcouleur"="Vcouleur" ,   "Vépaisseur" ="Vépaisseur" ,"Oœuf"="Oœuf"  ,      "Olait"="Olait"    ,   "Obeurre"="Obeurre"  ,   "Ovanille"="Ovanille"  ,  "Ocaramel"="Ocaramel" , "Ocitron" ="Ocitron"   , "Tdurcroq" ="Tdurcroq"  ,  "Tfriabilité"="Tfriabilité" ,"Tgranusabl"="Tgranusabl" , "Tfarineux" = "Tfarineux"  , "Tcraqcroust"="Tcraqcroust" ,"Tpâteux"="Tpâteux"  ,  "Tfondant"= "Tfondant" ,   "Gsalé"= "Gsalé"   ,    "Gsucré"="Gsucré"  ,    "Gœuf"="Gœuf"    ,    "Glait"="Glait"  ,     "Gbeurre" ="Gbeurre"  ,  "Gvanille"="Gvanille"  , "Gcaramel"= "Gcaramel"   , "Gcitron"="Gcitron" )),
                                                                                                                                                                                                                                                         hr(),
                                                                                                                                                                                                                                                         helpText("choisir les variable")),mainPanel (verbatimTextOutput("cinq2") ,plotOutput("six2")))))),
              
              tabPanel("Multivarite Analysis",tabsetPanel(
                tabPanel("Mean Table",DT::dataTableOutput("mtab")),
                tabPanel("1.scree Plot ",plotOutput('scree'),downloadButton(outputId="one",label="Download the plot"), DT::dataTableOutput('table2'),downloadButton(outputId="two",label="Download the data"),plotOutput("Projection"),downloadButton(outputId="three",label="Download the plot")),
                
                tabPanel("2.contribution of variables in construction",DT::dataTableOutput('table3'),downloadButton(outputId="four",label="Download the data"),"Contribution axe 1" ,plotOutput('plot1'),downloadButton(outputId="five",label="Download the plot"),"contribution axe 2",plotOutput('plot2'),downloadButton(outputId="sixx",label="Download the plot"),plotOutput("corr"),downloadButton(outputId="huhuh",label="Download the plot")),
                tabPanel("3.contribution of individuals in construction",DT::dataTableOutput('table4'),downloadButton(outputId="eight",label="Download the data"),"Contribution axe 1" ,plotOutput('plot3'),downloadButton(outputId="nine",label="Download the plot"),"contribution axe 2",plotOutput('plot4'),downloadButton(outputId="ten",label="Download the plot")),
                 tabPanel("4.individual Graph",plotOutput('plot5'),downloadButton(outputId="eleven",label="Download the plot")),
                tabPanel("5.Representation Quality",plotOutput('plot6'),downloadButton(outputId="twelve",label="Download the plot"))
              )),
              
              navbarMenu("More",
                         tabPanel("Cartography",h2("Mapping"),"VARIABLS",hr(),plotOutput("cartoo2") ,"Individuals", hr(),plotOutput("cartoo"),"Biplot",  hr(),plotOutput("cartoo3")),
                         tabPanel("Culstering",h2("Clustering"),plotOutput("clus"),hr(),plotOutput("clus2"))
              )
              
            )
  ))
